# Generated by Django 4.1.7 on 2023-03-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
